### ISSUE TITLE
Issue with Primer Spec PR Previews

### ISSUE THREAD

**Issue by jackphong** [eecs485staff/primer-spec#143]
I'm having some issues in the EECS 370 repo with the Build and upload website preview, the issue seems to be with the 
nokogiri-1.12.5-x86_64-linux package. Any ideas on how to get this feature working again?

![image](https://user-images.githubusercontent.com/46696737/147862569-1f6996df-e909-4948-8ed8-5936e12245d0.png)

raw text:
`bundle install
  /opt/hostedtoolcache/Ruby/3.1.0/x64/bin/bundle config set deployment true
  /opt/hostedtoolcache/Ruby/3.1.0/x64/bin/bundle config path /home/runner/work/project_1_spec/project_1_spec/vendor/bundle
  /opt/hostedtoolcache/Ruby/3.1.0/x64/bin/bundle install --jobs=4 --retry=3 --gemfile=/home/runner/work/project_1_spec/project_1_spec/Gemfile
  Fetching gem metadata from https://rubygems.org/.........
  nokogiri-1.12.5-x86_64-linux requires ruby version < 3.1.dev, >= 2.5, which is
  incompatible with the current version, ruby 3.1.0p0
  Error: Gemfile.lock probably needs updating. Run "bundle install" locally and commit changes. Exiting action
  Error: The process '/opt/hostedtoolcache/Ruby/3.1.0/x64/bin/bundle' failed with exit code 5
  Took   3.74 seconds`

**Comment by seshrs** [comment]
Thanks for reporting! As discussed in a private PR, the fix is to update the GitHub Actions workflow. I've fixed the documentation in https://github.com/seshrs/upload-to-primer-spec-preview/commit/1b127d5d0c1aa85dfe8f01682a5adee8eb034ba0, but I'll keep this issue open until I have made the changes to the EECS 280 and EECS 485 repos too.
