### ISSUE TITLE
[Mobile] AnchorJS link does not jump correctly in Safari

### ISSUE THREAD

**Issue by seshrs** [eecs485staff/primer-spec#17]
On Safari in iOS 12.4.1 on an iPhone X, clicking an AnchorJS link next to a heading jumps underneath the section (the section is hidden by the top bar).

The fix is probably to use the existing hyperlink click handler to also listen to AnchorJS link click events.

**Comment by bryanbraun** [comment]
Hey @seshrs, AnchorJS developer here. 👋 

This is a common situation with sticky headers, and I typically recommend fixing this with CSS where possible. You can see an example fix here: https://www.bryanbraun.com/anchorjs/#pages-with-a-sticky-navbar

I'd be happy to submit a PR if you want, I'd just need some guidance on how to build the project styles locally and where I should put custom styles (since it looks like most, if not all, of the styles in this project are sourced from the primer project).

**Comment by seshrs** [comment]
Hi @bryanbraun, thanks for dropping by! 😀

I hadn't thought to look for a CSS solution to this issue, this definitely simplifies the code too! I'll create a PR with your suggestion.
