### ISSUE TITLE
Enhanced Code Block multiline command syntax highlighting

### ISSUE THREAD

**Issue by awdeorio** [eecs485staff/primer-spec#182]
**Describe the bug**
A multiline command in an enhanced code block incorrectly color codes all but the first line.

**To Reproduce**
```
$ mapreduce-manager \
    --host localhost \
    --port 6000 \
    --hb-port 5999 \
    --log-file mapreduce-manager.log &
```

I'd like to use this for some long commands in the EECS 485 P4 [spec](https://eecs485staff.github.io/p4-mapreduce/#start-a-manager-and-workers)

**Expected behavior**
When backslashes are used to create a multiline command, all lines of the command should be colorcoded the same way.

**Screenshots**
<img width="408" alt="Screen Shot 2022-04-28 at 11 09 37 AM" src="https://user-images.githubusercontent.com/7503005/165784951-2ca32790-f3c7-4411-83d7-775d73327dbe.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Brave
 - Version: 1.38.109

**Comment by seshrs** [comment]
Thanks for reporting! This was fixed by #150, the fix is in v1.7.0. (The next time you push a commit to the `main` branch of the P4 repo, the spec will be rebuilt with the latest version of Primer Spec.)

That said, this issue _did_ help me discover a new bug introduced by #174 — clicking the "Copy all commands" button only copies the first line of a multi-line console command! I'm going to create a new issue to track this.
