### ISSUE TITLE
Spooky icons even when Spooky theme not chosen

### ISSUE THREAD

**Issue by eecs441staff** [eecs485staff/primer-spec#214]
**Describe the bug**
I'm seeing the Spooky theme icons for theme selection and the hamburger menu even when I haven't selected the Spooky theme.

**To Reproduce**
They just showed up.

**Expected behavior**
Normal icons shown when Spooky theme not chosen.

**Screenshots**
![Screenshot 2022-10-02 at 04 21 24](https://user-images.githubusercontent.com/43324101/193445002-d0f0024e-e62f-433e-9151-360db743e5a2.png)

**Desktop (please complete the following information):**
 - macOS Ventura 13.0
 - Safari
 - 16.1

**Comment by seshrs** [comment]
Oops! These were only meant to show up around Halloween 😬

I’ll push a fix right away. Thanks for informing me about this!

**Comment by seshrs** [comment]
Fixed in e858180f69f35e63592f4bbb9aacde6a99ecb2ee, and I've release v1.8.2 with the fixes. Again, thanks so much for reporting!

---

***Aside:***
You can expect the Halloween icons to appear as an Easter egg for a limited time from October 25 to November 5. 
https://github.com/eecs485staff/primer-spec/blob/c400fba77a2192b56c260250f70eca69afd47916/src_js/conditional_plugins/should_load_plugin.ts#L30-L33

If you don't want Easter eggs to be displayed on your website, then update your `_config.yml` to set [`disableJokes`](https://eecs485staff.github.io/primer-spec/docs/USAGE_ADVANCED.html#disablejokes-boolean) to `true`.
