### ISSUE TITLE
Sidebar links broken in preview

### ISSUE THREAD

**Issue by awdeorio** [eecs485staff/primer-spec#216]
**Describe the bug**
The links in the sidebar are broke in the GH-Actions-created preview

**To Reproduce**
1. Create PR and see the Generate spec preview GH Action run ([example](https://github.com/eecs485staff/p3-insta485-clientside/pull/626#issuecomment-1250254744))
2. Navigate to the preview
3. Click on something in the side bar

You'll see a broken link, e.g., https://preview.sesh.rs/previews/eecs485staff/p3-insta485-clientside/626/pages/eecs485staff/p3-insta485-clientside/setup_react.html

**Expected behavior**
Link should be something like https://preview.sesh.rs/previews/eecs485staff/p3-insta485-clientside/626/setup_react.html

**Comment by seshrs** [comment]
Very weird bug! My guess is that this is happening only now because GitHub Pages deployments have moved to GitHub Actions. But I'm going to need to debug this further.

**Comment by noah-weingarden** [comment]
Unfortunately, the sidebar tutorial inks are currently broken as described in this issue for the production build of [project 4](https://eecs485staff.github.io/p4-mapreduce/).

**Comment by seshrs** [comment]
😱  oof, thanks for raising! I'm looking into this now.

**Comment by seshrs** [comment]
I quickly suspected that the issue was related to the `baseurl` property, but it took me several embarrassing commits to properly fix [seshrs/build-primer-spec-action](https://github.com/seshrs/build-primer-spec-action) 😅 

If you're curious, this is the fix: https://github.com/seshrs/build-primer-spec-action/blob/e04cb027b517ccf0aa6ea99397d73375169cf6c0/action.yml#L16-L33

And if you're curious what `baseurl` does in Jekyll, here's a TLDR:
```
https://eecs485staff.github.io/p4-mapreduce/heapq.html
                                           ^^^^^^^^^^^ path
                              ^^^^^^^^^^^^^ baseurl (was being set to 'pages' by default for some reason)
^^^^^^^^^^^^ url ^^^^^^^^^^^^^
```

(Further reading: https://mademistakes.com/mastering-jekyll/site-url-baseurl/)

---

I took the liberty of re-running the [deploy job (attempt 2)](https://github.com/eecs485staff/p4-mapreduce/actions/runs/3349514831/attempts/2) for the P4 website. The links in the Sidebar now work!

**Comment by noah-weingarden** [comment]
Huh, that isn't very well-documented, is it? Thanks Sesh!
