### ISSUE TITLE
Spec doesn't print properly

### ISSUE THREAD

**Issue by rileyschnee** [eecs485staff/primer-spec#39]
**Describe the bug**
When I do a print preview or try to export a PDF, the text looks jumbled after the first couple of pages.

**To Reproduce**
1. Open a spec
2. On Chrome, click the three dots in the upper right corner of browser.
3. Click "Print"
4. View pages of spec

**Expected behavior**
I expect the pdf to have text like it appears on the screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/22105181/73489075-022f1d00-4378-11ea-829a-b69a3af7e378.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 79

**Additional context**

**Comment by seshrs** [comment]
Thanks for reporting this, @rileyschnee! Turns out that this is a Chrome bug — it’s been fixed, but it will take a few months before the fix merges with public Chrome. Until then, printing from other browsers should work. (See #38 for details.)

How much is this affecting you (and other students)? If needed, I can prioritize a fix for this semester.

**Comment by rileyschnee** [comment]
It doesn't affect me too much, knowing that I can print off other browsers. Maybe just a mention somewhere that printing isn't working on Chrome yet would be helpful?

**Comment by seshrs** [comment]
#40 adds a workaround for now. Let me know if you have further questions, or if you're still seeing this bug!
