### ISSUE TITLE
Emoji Mismatch

### ISSUE THREAD

**Issue by awdeorio** [eecs485staff/primer-spec#99]
**Describe the bug**
The `:white_check_mark:` emoji appears to differ from the GitHub version.

**To Reproduce**
Render a Markdown doc containing the `:white_check_mark:` :white_check_mark: emoji.

**Expected behavior**
<img width="227" alt="Screen Shot 2021-01-02 at 1 21 03 PM" src="https://user-images.githubusercontent.com/7503005/103463834-65020480-4cfd-11eb-9875-8957089208c0.png">

**Screenshots**
From https://eecs280staff.github.io/p1-stats/setup.html#visual-debugger

<img width="825" alt="Screen Shot 2021-01-02 at 1 22 00 PM" src="https://user-images.githubusercontent.com/7503005/103463855-85ca5a00-4cfd-11eb-97b5-6fe09dcc3f8c.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Frefox
 - Version: 84

**Comment by seshrs** [comment]
This is a really interesting observation!

I dug into this, and here's what I found. When you use GitHub-Flavored Emoji on Jekyll, GitHub Pages uses the [Jemoji plugin](https://github.com/jekyll/jemoji) to convert emoji short-codes into inline-images with `src="https://github.githubassets.com/images/icons/emoji/unicode/<unicode-codepoint>.png"`. So for instance, `:+1:` ([thumbs-up emoji, U+1F44D](https://emojipedia.org/emoji/%F0%9F%91%8D/)) is transformed into an image served from https://github.githubassets.com/images/icons/emoji/unicode/1f44d.png. Basically, Jemoji renders GitHub sprites of emojis, not actual emoji characters.

The emoji in question, `:white_check_mark:` ([U+2705](https://emojipedia.org/emoji/%E2%9C%85/)) is typically represented as a green-box with a white check-mark, but [this design is not necessarily standardized](https://emojipedia.org/check-mark-button/). The corresponding [GitHub sprite](https://github.githubassets.com/images/icons/emoji/unicode/2705.png) does **not** have the green box, and is what we see rendered with GitHub Pages.

Unfortunately, the best suggestion I have is to use native emoji instead of GitHub-Flavored Emoji. (So use ✅ instead of `:white_check_mark:`.) It's not ideal, and won't display the same way across all OSes, but maybe that's okay.

**Comment by awdeorio** [comment]
That was a very satisfying explanation!  Thanks for digging in to this!
